# -*- coding: utf-8 -*-
"""SemanticApp.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wlda5dFw6BCxWZ1d8pGXQf-dRF_sF7T1
"""

import streamlit as st
import pickle
import re

#vect=pickle.load(open("best-l-vect.pickle","rb"))

with open("best-l-vect.pickle", "rb") as f:
    vect = pickle.load(f)
#model=pickle.load(open("best-l-model.pickle","rb"))

with open("best-l-model.pickle", "rb") as g:
    model = pickle.load(g)
st.title("Deep Learning Based-Semantic Classification for Arabic: Case of Kalila w Dimna")
text=st.text_input("Please enter your text to semantic analysis")
cleaned_text = re.sub('[^؀-ۿ]+', ' ', str(text))
cleaned_text = re.sub('\s+', ' ', cleaned_text).strip()
X=vect.transform([cleaned_text]).toarray()
pred=model.predict(X)
if st.button("Semantic Prediction"):
  if pred==0:
    st.success("Your input text is semantically indexed as Not Animal")
  else:
    st.success("Your input text is semantically indexed as Animal")
